# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Gedanken und Notizen zu ...
tagline:          'Gedanken und Notizen zu...'
description:      'Open Source, GIS, Archäologie...'
url:              https://mk-archaeo.github.io

author:
  name:           'Marco Kultus'
  url:            https://twitter.com/mk-archaeo

github:
  repo:           https://github.com/mk-archaeo
